In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nakshatra\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\nakshatra\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\nakshatra\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 695.2 kB/s eta 0:00:14
   -- ------------------------------------- 0.5/9.9 MB 695.2 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/9.9 MB 688.8 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/9.9 MB 688.8 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/9.9 MB 688.8 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/9.9 MB 688.8 kB/s eta 0:00:14
   ---- ----------------------------------- 1.0/9.9 MB 456.0 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/9.9 MB 456.0 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.9 MB 502.3 kB/s eta 0:00:18
   ------ --------------------------------- 1.6/9.9 MB 553.3 kB/s eta 0:00:16
   ------- -------------------------------- 1.8/9.9 MB 588.3 kB/s eta 0:00:14
   ------- -------------------------------- 1.8/9.9 MB 588.3 kB/s eta 0:00:14
   -------- ------------------------------- 2.1/9.9 MB 608.4 kB/s eta 0:00:13
   --------- ------------------------------ 2.4/9.9 MB 652.0 kB/s eta 0:00:12
   ---------- ----------------------------- 2.6/9.9 MB 692.6 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.9 MB 692.6 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.9 MB 692.6 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.9 MB 692.6 kB/s eta 0:00:11
   ----------- ---------------------------- 2.9/9.9 MB 614.3 kB/s eta 0:00:12
   ------------ --------------------------- 3.1/9.9 MB 642.2 kB/s eta 0:00:11
   ------------- -------------------------- 3.4/9.9 MB 669.2 kB/s eta 0:00:10
   -------------- ------------------------- 3.7/9.9 MB 698.3 kB/s eta 0:00:09
   --------------- ------------------------ 3.9/9.9 MB 721.6 kB/s eta 0:00:09
   ---------------- ----------------------- 4.2/9.9 MB 736.5 kB/s eta 0:00:08
   ------------------ --------------------- 4.5/9.9 MB 744.9 kB/s eta 0:00:08
   ------------------ --------------------- 4.5/9.9 MB 744.9 kB/s eta 0:00:08
   ------------------- -------------------- 4.7/9.9 MB 760.1 kB/s eta 0:00:07
   -------------------- ------------------- 5.0/9.9 MB 769.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.2/9.9 MB 788.3 kB/s eta 0:00:06
   ---------------------- ----------------- 5.5/9.9 MB 804.7 kB/s eta 0:00:06
   ----------------------- ---------------- 5.8/9.9 MB 814.2 kB/s eta 0:00:06
   ------------------------ --------------- 6.0/9.9 MB 827.6 kB/s eta 0:00:05
   -------------------------- ------------- 6.6/9.9 MB 865.3 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 876.4 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.9 MB 889.5 kB/s eta 0:00:04
   ------------------------------ --------- 7.6/9.9 MB 920.6 kB/s eta 0:00:03
   ------------------------------- -------- 7.9/9.9 MB 930.0 kB/s eta 0:00:03
   -------------------------------- ------- 8.1/9.9 MB 947.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 980.0 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 983.6 kB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 983.6 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 974.0 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 971.6 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 979.0 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 975.4 kB/s  0:00:10
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
#Series
a=[10,20,30]
pd.Series(a)

0    10
1    20
2    30
dtype: int64

In [5]:
b=[2.3,4.5,6.7]
pd.Series(b)

0    2.3
1    4.5
2    6.7
dtype: float64

In [6]:
c=['star','moon']
pd.Series(c)

0    star
1    moon
dtype: str

In [7]:
d=[True,False]
pd.Series(d)

0     True
1    False
dtype: bool

In [8]:
e=[2+3j,4+5j]
pd.Series(e)

0    2.0+3.0j
1    4.0+5.0j
dtype: complex128

In [11]:
f={'name':['star','moon','sun'],'marks':[78,98,89]}
pd.Series(f)

name     [star, moon, sun]
marks         [78, 98, 89]
dtype: object

In [10]:
#DataFrame
f={'name':['star','moon','sun'],'marks':[78,98,89]}
pd.DataFrame(f)

   name  marks
0  star     78
1  moon     98
2   sun     89

In [ ]:
i={'name':['earth','mars','jupy'],'sub':[45,56,78],'

In [16]:
data=pd.read_csv('jun9(sample) - Sheet1.csv')
data

   ID       NAME            MAIL ID
0   1  Nakshatra     star@gmail.com
1   2    Sudheer     moon@gmail.com
2   3     Hasini    earth@gmail.com
3   4     Satish     mars@gmail.com
4   5     Vishnu    venus@gmail.com
5   6  Chaitanya  jupiter@gmail.com
6   7     Lahari   uranus@gmail.com

In [17]:
data.columns               #prints columns

Index(['ID', 'NAME', 'MAIL ID'], dtype='str')

In [18]:
data.shape                #prints (rows,columns)

(7, 3)

In [20]:
data.info                  #prints table

<bound method DataFrame.info of    ID       NAME            MAIL ID
0   1  Nakshatra     star@gmail.com
1   2    Sudheer     moon@gmail.com
2   3     Hasini    earth@gmail.com
3   4     Satish     mars@gmail.com
4   5     Vishnu    venus@gmail.com
5   6  Chaitanya  jupiter@gmail.com
6   7     Lahari   uranus@gmail.com>

In [22]:
data=pd.read_csv('cumulative.csv')
data

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,9560,10031643,K07984.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,0,...,-152.0,4.296,0.231,-0.189,1.088,0.313,-0.228,298.74921,46.973351,14.478
9560,9561,10090151,K07985.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,1,...,-166.0,4.529,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082
9561,9562,10128825,K07986.01,NaN,CANDIDATE,CANDIDATE,0.497,0,0,0,...,-220.0,4.444,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757
9562,9563,10147276,K07987.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.021,0,0,1,...,-236.0,4.447,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385
9563,9564,10156110,K07989.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,1,...,-225.0,4.385,0.054,-0.216,1.193,0.410,-0.137,297.00977,47.121021,14.826

In [23]:
data.columns

Index(['rowid', 'kepid', 'kepoi_name', 'kepler_name', 'koi_disposition',
       'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss',
       'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1',
       'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1',
       'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2',
       'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth',
       'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1',
       'koi_prad_err2', 'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 'koi_insol',
       'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_tce_delivname', 'koi_steff', 'koi_steff_err1', 'koi_steff_err2',
       'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad',
       'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='str')

In [24]:
data.shape

(9564, 50)

In [25]:
data.info

<bound method DataFrame.info of       rowid     kepid kepoi_name   kepler_name koi_disposition  \
0         1  10797460  K00752.01  Kepler-227 b       CONFIRMED
1         2  10797460  K00752.02  Kepler-227 c       CONFIRMED
2         3  10811496  K00753.01           NaN  FALSE POSITIVE
3         4  10848459  K00754.01           NaN  FALSE POSITIVE
4         5  10854555  K00755.01  Kepler-664 b       CONFIRMED
...     ...       ...        ...           ...             ...
9559   9560  10031643  K07984.01           NaN  FALSE POSITIVE
9560   9561  10090151  K07985.01           NaN  FALSE POSITIVE
9561   9562  10128825  K07986.01           NaN       CANDIDATE
9562   9563  10147276  K07987.01           NaN  FALSE POSITIVE
9563   9564  10156110  K07989.01           NaN  FALSE POSITIVE

     koi_pdisposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0           CANDIDATE      1.000              0              0              0
1           CANDIDATE      0.969              0              0              0
2      FALSE POSITIVE      0.000              0              1              0
3      FALSE POSITIVE      0.000              0              1              0
4           CANDIDATE      1.000              0              0              0
...               ...        ...            ...            ...            ...
9559   FALSE POSITIVE      0.000              0              0              0
9560   FALSE POSITIVE      0.000              0              1              1
9561        CANDIDATE      0.497              0              0              0
9562   FALSE POSITIVE      0.021              0              0              1
9563   FALSE POSITIVE      0.000              0              0              1

      ...  koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  \
0     ...           -81.0      4.467           0.064          -0.096
1     ...           -81.0      4.467           0.064          -0.096
2     ...          -176.0      4.544           0.044          -0.176
3     ...          -174.0      4.564           0.053          -0.168
4     ...          -211.0      4.438           0.070          -0.210
...   ...             ...        ...             ...             ...
9559  ...          -152.0      4.296           0.231          -0.189
9560  ...          -166.0      4.529           0.035          -0.196
9561  ...          -220.0      4.444           0.056          -0.224
9562  ...          -236.0      4.447           0.056          -0.224
9563  ...          -225.0      4.385           0.054          -0.216

      koi_srad  koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag
0        0.927          0.105         -0.061  291.93423  48.141651      15.347
1        0.927          0.105         -0.061  291.93423  48.141651      15.347
2        0.868          0.233         -0.078  297.00482  48.134129      15.436
3        0.791          0.201         -0.067  285.53461  48.285210      15.597
4        1.046          0.334         -0.133  288.75488  48.226200      15.509
...        ...            ...            ...        ...        ...         ...
9559     1.088          0.313         -0.228  298.74921  46.973351      14.478
9560     0.903          0.237         -0.079  297.18875  47.093819      14.082
9561     1.031          0.341         -0.114  286.50937  47.163219      14.757
9562     1.041          0.341         -0.114  294.16489  47.176281      15.385
9563     1.193          0.410         -0.137  297.00977  47.121021      14.826

[9564 rows x 50 columns]>